### ISSUE TITLE
Unable to parse file

### ISSUE THREAD

**Issue by rezmuh** [elegoff/sonar-rust#26]
Hi, first of all, thanks for creating this plugin.

I just started using this plugin (version 0.0.4) on Sonarqube 8.5.1 deployed on Kubernetes. I integrated Sonarqube through GitHub actions. However, I noticed that when sending data to Sonarqube, I got the following error:

```
...snip source code
ERROR: Unable to parse file: <path to/file>.rs
ERROR: Parse error at line 367 column 66:
...snip source code
```

When I looked at Sonarqube, there are a lot of files missing (possibly due to the error above).

Is this a known issue?

**Comment by elegoff** [comment]
Thanks for this feedback. I suspect some of your source files are not correctly handled by the current Grammar implementation. It is some kind of work in progress right now and so far only tested on some few projects.

It is hard to anticipate every Rust source syntax and I would be curious to know more about your specific parsing issue.

Is it possible for you to share the source files ? That would help improving the parsing and understand what goes wrong in your specific context (If that is an open source project, sharing the repository would be perfect)

Alternatively , you could send private messages at _sonar-rust@pm.me_ with some of those files , that would help improve the Rust parser of this plugin

**Comment by rezmuh** [comment]
Sure, i'll send that over email.

**Comment by elegoff** [comment]
Hello @rezmuh , I did not get the files , would you have the chance to send them ?
