### ISSUE TITLE
PR Decoration / Failing PR’s on GitHub / GitHub EE

### ISSUE THREAD

**Issue by Panajev** [elegoff/sonar-rust#28]
Hello @elegoff 

We are using this plugin on our company SonarQube instance (soon to be updated to the 9.0.x version) and I would like to understand how this plugin can be used to support PR decoration with SonarQube if it does support it and what you think might be the blockers/problems in adding what is required to support it.

Ultimately, ensuring the PR fails or passes a Sonar Quality gate is the goal we want to achieve with Rust and if we could show it visibly on a GitHub Enterprise Edition setup too it would be very important to us.

Thank you in advance for your support(and for the plugin of course :)).

Kind Regards,

Goffredo Marocchi

**Comment by elegoff** [comment]
Hello Goffredo,

There is nothing specific in this plugin that would prevent you from using Pull Requests Decoration. It should behave as any other language plugins and it should comply to your Quality Gates configuration.
For example if this plugin raises more issues that your QG is defining , it will fail the QG

I have not tested this Rust plugin on a SonarQube 9.0 yet but will do that soon

Thanks again for considering this plugin on your company instance

Regards,

Eric
