### ISSUE TITLE
Duplication code configuration

### ISSUE THREAD

**Issue by jaudiger** [elegoff/sonar-rust#40]
Hi,

How could I prevent sonarqube to find duplicated code inside the unit tests? I currently have a project with a lot of duplication in my unit tests, but since, it's not my priority to solve them, I was searching for an option to hide them.

Thanks in advance.

**Comment by elegoff** [comment]
Hello Jeremy , 

The question is actually not specific to this plugin

The official SonarQube doc has this : https://docs.sonarqube.org/8.9/project-administration/narrowing-the-focus/#header-4

Alternatively to the suggest solution from the UI, you could also use the property `sonar.cpd.exclusions` in your sonar-project.properties to set the list of folders where the duplication calculation should be ignored.

I hope this helps

**Comment by jaudiger** [comment]
Hi @elegoff,

My problem comes when the source and the unit tests are together in the same file which is common in Rust. And I don't really know how to inform sonarqube to not look for a certain part of the file. Or maybe with the link you sent, do you think I could have a sort of regex to inform sonarqube to not look for function annotated with tests?

**Comment by elegoff** [comment]
As far I know In SonarQube, duplication exclusion can only be handled at file level.
You cannot exclude code blocks from duplication detection.

One option would be to use the **Ignore Issues in Blocks exclusion** settings. Navigate to the **Project Settings > General Settings > Analysis Scope** and you'll see space for a regular expression for the start and end of a block .

 Be careful with the regexes and check them in one of the online checkers – particularly the End block regex. If you get that one wrong you'll exclude code until you hit the end of the file. Also note that in that case **it will ignore all the issue as well(not just duplication)** for particular block of code.

**Comment by jaudiger** [comment]
Thanks for the clarification @elegoff. I tried your suggestions, unfortunately, for certain reasons, Sonarqube stopped reporting the coverage for the whole file when I set my Start Block regex. The regex was quite simple and was only targetting the annotations of my unit tests (`#[test]` or `#[tokio::test]`). Well, I guess this issue has nothing to do with this plugin. Feel free to close it. And thanks anyway.

Just one last question (for my understanding): does Sonarqube embed an analyzer that is agnostic of the language to detect code duplication?

**Comment by elegoff** [comment]
You are correct that SonarQube calculates duplication in way that is agnostic to the language.
Language analysers can only decide to override certain default parameters of the calculation
See the "Language specific details" section of the [Duplication doc](https://docs.sonarqube.org/8.9/user-guide/metric-definitions/#header-2)
I will now close this as this is indeed not specific to this plugin. Feel free to reach out to the official [SonarQube Community Forum](https://community.sonarsource.com/) if you need more generic details

**Comment by elegoff** [comment]
After a second thought the plugin implementers have actually the ability to exclude some of the lines of code to be sent to the duplications calculation on SonarQube.

I have merged a PR on master providing the new (boolean) parameter `community.rust.cpd.ignoretests` 

See https://github.com/elegoff/sonar-rust/blob/master/DOC.md#ignore-duplications-on-unit-tests

**Comment by jaudiger** [comment]
Well, thank you! I'll try this after the next release of this plugin.

**Comment by gmli** [comment]
Hi, I’ve tried the "Ignore Issues in Blocks" as well as the `community.rust.cpd.ignoretests=true` but none of them exclude duplications of the test blocks.
Do you know if there is some regression @elegoff ?
