### ISSUE TITLE
Can't download this plugin with LTS chart

### ISSUE THREAD

**Issue by yanis-incepto** [elegoff/sonar-rust#50]
Hello,
When I use the Sonar’s chart with the LTS version 1.0.26, I can’t download this plugins.
Here’s a part of my helmfile (part about the plugins) :

plugins:
  install:
  - https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar

When I do my helmfile apply, there are no installed plugins.
Thanks for your help

**Comment by elegoff** [comment]
Hello Yanis,

I am not that much familiar with Helm charts and this looks like a generic problem over any kind of third-party plugins and not only this specific sonar-rust plugin

You might want to double-check that[ part of the SonarQube docs ](https://docs.sonarqube.org/latest/setup/sonarqube-on-kubernetes/#header-1 about K8s env recommendations)

Other than that it could be something about **Risk Consent**, it basically blocks third-party plugin development until you accept the risk (read more about this in [Use 3rd-party plugins at your own risk](https://blog.sonarsource.com/use-3rd-party-plugins-at-your-own-risk)).

You could check the following 

* accept the Risk Consent in the SonarQube UI: **Administration > Marketplace > I understand the risk**
* uninstall and re-install the Helm chart, and check if plugins can now be deployed

**Comment by yanis-incepto** [comment]
Hello,
Thanks you for your answers, I sent a ticket to Sonar too and in fact, the issue was coming from their side, they answered that they'll work on it !
