### ISSUE TITLE
Clippy reports fail to load if stored in a subdirectory or different file tree

### ISSUE THREAD

**Issue by andrewm-aero** [elegoff/sonar-rust#65]
[This line](https://github.com/elegoff/sonar-rust/blob/45acb3b242986515e3217309c20e29da08243ad2/community-rust-plugin/src/main/java/org/elegoff/plugins/communityrust/clippy/ClippySensor.java#LL110C19-L110C19) assumes that the clippy report file is stored directly in the directory clippy was run from.

This prevents storing the report out-of-tree or in a subdirectory (e.g. target/).

Ideally, there should be some way to specify the "root" (or just assume the analysis root is the root for all source paths).

If this is not possible, please update the documentation to explicitly state this requirement.

**Comment by elegoff** [comment]
It should actually be already possible to store and fetch the clippy report(s) from other locations than the root of the project

That is done via the **community.rust.clippy.reportPaths** analysis parameter , where you can define the report location via either a relative path  to the root of your project, e.g target/: 
`community.rust.clippy.reportPaths=target/my-clippy-report.json`
or even an absolute path, e.g
`community.rust.clippy.reportPaths=/var/data/my-clippy-report.json`

By the way it does not have to be a single report , eg
`community.rust.clippy.reportPaths=target/my-first-clippy-report.txt, target/a-second-clippy-report.txt` (with a co,mma delimiter) should also work

Let me know if I did not understand your question correctly

**Comment by elegoff** [comment]
A PR to fix https://github.com/elegoff/sonar-rust/pull/66 is now merged on the master branch
